apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: bookstore-web
    environment: {{ .Values.global.environment }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.secrets.keyVault.tenantId }}
  {{- end }}
