apiVersion: v2
name: bookstore
description: A Helm chart for the Bookstore .NET 10 Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - bookstore
  - dotnet
  - aspnetcore
maintainers:
  - name: Bookstore Team
home: https://github.com/RobertoBorges/PHP-Bookstore-Website-Example
