apiVersion: v2
name: bookstore
description: A Helm chart for Bookstore .NET 10 application on Azure Kubernetes Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - bookstore
  - dotnet
  - azure
  - aks
maintainers:
  - name: Bookstore Team
home: https://github.com/RobertoBorges/PHP-Bookstore-Website-Example
sources:
  - https://github.com/RobertoBorges/PHP-Bookstore-Website-Example
